# Generated by Django 4.1.4 on 2023-01-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitoblar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ona_tili', models.TextField()),
                ('jismoniy_tarbiya', models.TextField()),
                ('tasviriy_sanat', models.TextField()),
                ('geografiya', models.TextField()),
                ('informatika', models.TextField()),
                ('kimyo', models.TextField()),
                ('musiqa', models.TextField()),
                ('fizika', models.TextField()),
                ('algebra', models.TextField()),
                ('geometriya', models.TextField()),
                ('biologiya', models.TextField()),
                ('tarix', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fulname', models.CharField(max_length=30)),
                ('Tugilgan_yili', models.DateField(max_length=30)),
                ('Lavozimi', models.CharField(max_length=30)),
                ('Maoshi', models.TextField()),
                ('Oquvchisi', models.TextField()),
            ],
        ),
    ]
