# Generated by Django 4.1.2 on 2022-11-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_admins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student1A',
        ),
    ]
