# Generated by Django 4.1.2 on 2022-11-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0010_student10a_student11a_student3a_student4a_student5a_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_10F',
        ),
        migrations.DeleteModel(
            name='Student_11F',
        ),
    ]
