# Generated by Django 4.1.2 on 2022-12-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0015_profile_alter_ch_groups_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
