# Generated by Django 4.1.4 on 2022-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0017_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='pastal_code',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='fullname',
            field=models.CharField(max_length=70),
        ),
    ]
